{% set name = "skyproj" %}
{% set version = "2.0.0" %}
{% set sha256 = "41be00283b11e785364c8ea78eb3c706d2e55972638646ee2ccb5c3aecbb6756" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >={{ python_min }}
    - numpy
    - astropy-base >=4.0
    - matplotlib-base >=3.8
    - healsparse
    - hpgeom
    - pyproj >=3.1

test:
  imports:
    - skyproj
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/lsstdesc/skyproj
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Sky mapping with matplotlib and PROJ
  description: |
    skyproj provides an astronomically oriented interface to
    ploting sky maps based on matplotlib and PROJ. skyproj is
    intended as the primary visualization tool for healsparse
    maps, which provide high resolution maps in a memory efficent way.
    skyproj can create interactive visualizations of healsparse and
    healpy maps that dynamically change resolution.
  dev_url: https://github.com/lsstdesc/skyproj

extra:
  recipe-maintainers:
    - erykoff
